name: Release

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        uses: TheDoctor0/zip-release@0.7.6
        
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "release.zip"
