name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true

jobs:
  zip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Zip files
        uses: TheDoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: "release_${{ github.event.inputs.tag }}.zip"
          exclusions: '*.git*'

      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "release_${{ github.event.inputs.tag }}.zip"
          tag: "${{ github.event.inputs.tag }}"

