name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true

jobs:
  zip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Zip files
        uses: TheDoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: "release-${{ github.event.inputs.tag }}.zip"
          exclusions: '*.git*'

      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "release-${{ github.event.inputs.tag }}.zip"
          tag: "${{ github.event.inputs.tag }}"

      - name: Create Master Release
        uses: TheDoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: "release-cdda-compack-main.zip"
          exclusions: '*.git*'

      - name: Delete Master Release
        run: gh release delete cdda-compack-main --cleanup-tag
        env:
          GH_TOKEN: ${{ github.token }}        

      - name: Upload Master Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "release-cdda-compack-main.zip"
          tag: "cdda-compack-main"          

